// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icwrgkzkljvlrmobxpux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd3Jna3prbGp2bHJtb2J4cHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODI5MTQsImV4cCI6MjA2MzE1ODkxNH0.PRQsEn4h0AnxTxfKLrPh7hrN-7U4o_ew-GXolIY-xmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);